"use client";

import { useEffect, useMemo, useState } from "react";

type Plan = { name:string; units:number; price:number; milkTons:number; milkCostPerTon:number; maintenance:number; depreciation:number; transport:number; marketing:number; salaries:number; rent:number; interest:number; carriedLosses:number; bonusRate:number; taxRate:number; openingCash:number; loanReceived:number; machinePurchase:number; principalRepaid:number; };
const baseline:Plan={name:"Season 2 working plan",units:50000,price:2,milkTons:2.5,milkCostPerTon:20000,maintenance:1800,depreciation:4375,transport:5000,marketing:1000,salaries:10000,rent:17000,interest:0,carriedLosses:0,bonusRate:5,taxRate:10,openingCash:43825,loanReceived:0,machinePurchase:0,principalRepaid:0};
const lean:Plan={...baseline,name:"Margin-first",units:45000,price:2.25,milkTons:2.25,transport:4500,marketing:1500};
const growth:Plan={...baseline,name:"Growth-first",units:65000,price:2,milkTons:3.25,maintenance:2000,transport:6500,marketing:5000};
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}); const fmt=(v:number)=>money.format(v).replace("$","SH ");
const fields:{key:keyof Plan;label:string;suffix:string;hint?:string}[]=[
 {key:"units",label:"Units sold",suffix:"units"},{key:"price",label:"Price per unit",suffix:"SH"},{key:"milkTons",label:"Milk purchased",suffix:"tons"},{key:"milkCostPerTon",label:"Milk cost per ton",suffix:"SH"},{key:"maintenance",label:"Machine maintenance",suffix:"SH"},{key:"depreciation",label:"Depreciation",suffix:"SH",hint:"Non-cash expense"},{key:"transport",label:"Transport",suffix:"SH"},{key:"marketing",label:"Marketing",suffix:"SH"},{key:"salaries",label:"Fixed salaries",suffix:"SH"},{key:"rent",label:"Premises rent",suffix:"SH"},{key:"interest",label:"Loan interest",suffix:"SH"},{key:"carriedLosses",label:"Carried tax losses",suffix:"SH"},{key:"bonusRate",label:"Bonus rate",suffix:"%"},{key:"taxRate",label:"Game tax rate",suffix:"%"},{key:"openingCash",label:"Opening cash",suffix:"SH"},{key:"loanReceived",label:"Loan received",suffix:"SH"},{key:"machinePurchase",label:"Machine purchase",suffix:"SH"},{key:"principalRepaid",label:"Loan principal repaid",suffix:"SH"}
];
const premises=[['A',12000,.3,1],['B',10000,.4,1],['C',12000,.3,1],['D',17000,.1,1],['E',15000,.2,2],['F',16000,.2,3]];
const machines=[['1',72000,35000,1800,4375],['2',120000,95000,2900,11875],['3',68000,38000,2100,4750],['4',95000,70000,2900,8750],['5',45000,28000,1300,3500],['6',110000,90000,2900,11250]];
function calc(p:Plan){const revenue=p.units*p.price,milk=p.milkTons*p.milkCostPerTon,cashOps=milk+p.maintenance+p.transport+p.marketing+p.salaries+p.rent+p.interest,grossProfit=revenue-milk-p.maintenance-p.depreciation,bonus=Math.max(0,grossProfit)*p.bonusRate/100,profitBeforeTax=grossProfit-p.transport-p.marketing-bonus-p.salaries-p.rent-p.interest,lossUsed=Math.min(Math.max(0,profitBeforeTax),p.carriedLosses),taxable=Math.max(0,profitBeforeTax-lossUsed),tax=taxable*p.taxRate/100,netProfit=profitBeforeTax-tax,closingCash=p.openingCash+p.loanReceived+revenue-cashOps-bonus-tax-p.machinePurchase-p.principalRepaid,lossPoolEnd=Math.max(0,p.carriedLosses-lossUsed)+Math.max(0,-profitBeforeTax);return{revenue,milk,cashOps,grossProfit,profitBeforeTax,bonus,tax,taxable,lossUsed,lossPoolEnd,netProfit,closingCash,margin:revenue?netProfit/revenue:0};}
export default function Home(){const[plan,setPlan]=useState<Plan>(baseline),[active,setActive]=useState("Custom plan"),[showPrompt,setShowPrompt]=useState(false);const result=useMemo(()=>calc(plan),[plan]);
 const apply=(p:Plan)=>{setPlan({...p});setActive(p.name)}; const edit=(k:keyof Plan,v:string)=>{setPlan(o=>({...o,[k]:Number(v)||0}));setActive("Custom plan")};
 useEffect(()=>{const c=document.modelContext;if(!c?.registerTool)return;const controller=new AbortController();void c.registerTool({name:"read_season_2_outlook",title:"Read Season 2 outlook",description:"Returns the current Season 2 forecast and cash outcome.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({strategy:active,revenue:result.revenue,netProfit:result.netProfit,closingCash:result.closingCash})},{signal:controller.signal});return()=>controller.abort()},[active,result]);
 const strategies=[{p:lean,tone:"steady",desc:"Protect cash while seeking a stronger price."},{p:growth,tone:"bold",desc:"Push volume with a larger milk and marketing commitment."}];
 return <main><section className="topbar"><div className="brand"><span className="mark">P/G</span><span>Pork & Garlic</span></div><div className="season-pill">YEAR 1 CLOSED <b>→</b> SEASON 2</div><button className="prompt-button" onClick={()=>setShowPrompt(!showPrompt)}>{showPrompt?"Hide build prompt":"Show build prompt"}</button></section>
 <section className="intro"><div><p className="eyebrow">Decision workspace</p><h1>Make Season 2<br/><em>earn its place.</em></h1><p className="lede">Start with your verified Season 1 cash position, tune the operational levers, and compare two practical paths before you commit.</p></div><div className="year-one"><p>YEAR 1 · SEASON 1</p><strong>{fmt(43825)}</strong><span>cash available at the start of Season 2</span><div><small>50,000 units × SH 2</small><small>SH 100,000 revenue</small></div></div></section>
 {showPrompt&&<section className="prompt-panel"><p className="eyebrow">Reusable prompt</p><p>Create an advanced interactive Season 2 business-game decision tool for Pork & Garlic. Preload Year 1 Season 1: 50,000 units at SH 2; 2.5 tons of milk costing SH 50,000; maintenance SH 1,800; depreciation SH 4,375; transport SH 5,000; marketing SH 1,000; salaries SH 10,000; rent SH 17,000; interest SH 0; carried tax losses SH 0; bonus 5%; game tax 10%; opening cash SH 100,000; loan SH 0; machine purchase SH 35,000; principal repaid SH 0; verified Season 2 opening cash SH 43,825. Provide editable inputs and two Season 2 strategies, calculating revenue, cash expenses, profit, bonus, tax and closing cash live. Clearly label depreciation as non-cash and make every number change the relevant output.</p></section>}
 <section className="strategy-section"><div className="section-heading"><div><p className="eyebrow">Two starting plays</p><h2>Choose a direction, then tune it.</h2></div><p>These are modeled starting points, not fixed answers.</p></div><div className="strategy-grid">{strategies.map(({p,tone,desc})=>{const r=calc(p);return <article className={`strategy-card ${tone}`} key={p.name}><div><span className="strategy-label">{p.name}</span><h3>{tone==="steady"?"Trade volume for price discipline.":"Put cash behind volume."}</h3><p>{desc}</p></div><dl><div><dt>Revenue</dt><dd>{fmt(r.revenue)}</dd></div><div><dt>Closing cash</dt><dd>{fmt(r.closingCash)}</dd></div><div><dt>Net profit</dt><dd>{fmt(r.netProfit)}</dd></div></dl><button onClick={()=>apply(p)}>Use {p.name} <span>→</span></button></article>})}</div></section>
 <section className="rule-picker"><div><p className="eyebrow">Rules loaded from the handout</p><h2>Select premise and machine assumptions</h2><p>Choosing a premise updates the seasonal rent and transport rate. Choosing a machine updates its purchase, maintenance and eight-season depreciation values; set units sold to no more than the capacity of rented machine slots.</p></div><div className="rule-tables"><div><h3>Premises</h3>{premises.map(([n,r,t,s])=><button key={String(n)} onClick={()=>setPlan(o=>({...o,rent:Number(r),transport:o.units*Number(t)}))}><b>{n}</b><span>SH {r.toLocaleString()} rent · SH {t}/sold unit · {s} slot{s===1?'':'s'}</span></button>)}</div><div><h3>Machines</h3>{machines.map(([n,c,p,m,d])=><button key={String(n)} onClick={()=>setPlan(o=>({...o,machinePurchase:Number(p),maintenance:Number(m),depreciation:Number(d)}))}><b>Machine {n}</b><span>{Number(c).toLocaleString()} capacity · SH {Number(p).toLocaleString()} buy · SH {m} maintenance</span></button>)}</div></div></section>
 <section className="workspace"><div className="inputs"><div className="input-head"><div><p className="eyebrow">Active plan</p><h2>{active}</h2></div><button onClick={()=>apply(baseline)}>Reset inputs</button></div><div className="input-grid">{fields.map(({key,label,suffix,hint})=><label key={key}><span>{label}{hint&&<i title={hint}>i</i>}</span><div className="number-field"><input aria-label={label} type="number" min="0" step={key==="price"||key==="milkTons"?"0.01":"1"} value={plan[key] as number} onChange={e=>edit(key,e.target.value)}/><b>{suffix}</b></div></label>)}</div></div>
 <aside className="results"><p className="eyebrow">Live forecast</p><h2>Season 2 outcome</h2><div className="primary-result"><span>Expected closing cash</span><strong>{fmt(result.closingCash)}</strong><small>{result.closingCash>=plan.openingCash?"Cash builds over the season":"Cash falls over the season"}</small></div><dl className="breakdown"><div><dt>Revenue</dt><dd>{fmt(result.revenue)}</dd></div><div><dt>Milk cost</dt><dd>−{fmt(result.milk)}</dd></div><div><dt>Cash operating costs</dt><dd>−{fmt(result.cashOps-result.milk)}</dd></div><div><dt>Depreciation <small>non-cash</small></dt><dd>−{fmt(plan.depreciation)}</dd></div><div><dt>Gross profit</dt><dd>{fmt(result.grossProfit)}</dd></div><div><dt>Bonus</dt><dd>−{fmt(result.bonus)}</dd></div><div><dt>Loss pool at end</dt><dd>{fmt(result.lossPoolEnd)}</dd></div><div><dt>Game tax</dt><dd>−{fmt(result.tax)}</dd></div></dl><div className="profit-line"><span>Net profit</span><strong>{fmt(result.netProfit)}</strong><small>{(result.margin*100).toFixed(1)}% margin</small></div><p className="formula-note">Rules applied: bonus is 5% of positive gross profit; tax is 10% after eligible loss-pool use. Machine purchases and loan principal change cash, not profit; interest changes profit.</p></aside></section><footer>Season 1 ending cash is used as your Season 2 opening cash. Change any assumption above to test the impact.</footer></main>;
}
